id: AEDD4AE3C
title: The Summoning of Longevity from Chimé Pakmé Nyingtik
type: translation
pechas:
- I0FA22BA0
- I358FA6A6
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:33:23.545245
  last_modified_at: 2023-01-04 11:33:23.545259
  collections:
  - Chokgyur Dechen Lingpa
  - Works of Tibetan Masters
alignment_to_base:
  I0FA22BA0/40AF: '6954'
  I358FA6A6/0035: '6954'
